### ISSUE TITLE
Definer output af ML modellen

### ISSUE THREAD

**Issue by MikaelVM** [P8-Team/App#35]

**Comment by MikaelVM** [comment]
Som defineret i P8-Team/Report#19 burde outputtet her ende ud med en form for  "identification"

Umiddelbare forslag er at denne identifikation ender ud med at definere et specifikt kamera, så vi kan lave antagelser for den transmitter power ud fra det.

**Comment by Kaliahh** [comment]
Identification er <type (kamera, mikrofon, osv), manufacturer (Google, LittleElf, osv), model (KC-200), transmission power (-6 dbm, -20 dbm, osv)>
