### ISSUE TITLE
Omdan RSSI (eller dbm?) til afstand

### ISSUE THREAD

**Issue by Kaliahh** [P8-Team/App#8]
Gør hvad titlen siger

**Comment by LauJosefsen** [comment]
Det eneste der vil være korrekt at konveretere DBm til er nok mW, men det er ikke noget vi har lyst til, da DBm gerne skulle være mere lineær med afstand end mW pga inverse-square law. 

Det ville ikke give meget mening at prøve at konvertere til afstand, da det kommer an på afsenderstyrken. Det kan dog godt bruges til relativ multilateration (altså DBm)

https://www.electronicdesign.com/technologies/communications/article/21796484/understanding-wireless-range-calculations
